FROM alpine

RUN apk update \
&& apk upgrade \
&& apk add --no-cache tzdata \
&& cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime\
&& echo "Asia/Taipei" > /etc/timezone \
&& date \
&& apk del tzdata \
&& apk add --no-cache openssh-client \
&& rm  -rf /tmp/* /var/cache/apk/* \
&& ssh-keygen -q -t ed25519 -N '' -f /root/.ssh/id_ed25519 \
&& cat ~/.ssh/id_ed25519.pub | cat - >> ~/.ssh/authorized_keys
CMD ["/bin/sh"]