FROM alpine

LABEL  authors=Spawn6123

ARG PASSWORD

RUN apk update \
&& apk upgrade \
&& apk add --no-cache tzdata \
&& cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime\
&& echo "Asia/Taipei" > /etc/timezone \
&& date \
&& apk del tzdata \
&& apk add --no-cache python3 \
&& apk add --no-cache openssh \
&& apk add --no-cache openrc \
&& mkdir ~/.ssh/ \
&& rc-update add sshd \
&& /usr/bin/ssh-keygen -A \
&& rm  -rf /tmp/* /var/cache/apk/* \
&& sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
&& echo "root:${PASSWORD}" | chpasswd
COPY authorized_keys /root/.ssh/
RUN chmod 600 /root/.ssh/authorized_keys
#ENTRYPOINT ["/etc/init.d/sshd start"]

EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]